# _config.yml

title: Buku Resep Keluarga
description: Kumpulan resep masakan turun-temurun dari keluarga kami.
baseurl: "/resep-keluarga"
url: "https://adityacprtm.github.io"

plugins:
  - jekyll-seo-tag

# Versi 2 - Paksa build ulang
