backend:
  name: github
  repo: adityacprtm/resep-keluarga
  branch: main

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "posts"
    label: "Resep"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "recipe" }
      - { label: "Judul Resep", name: "title", widget: "string" }
      - { label: "Penulis / Sumber", name: "author", widget: "string" }
      - {
          label: "Gambar Utama",
          name: "image",
          widget: "image",
          required: false,
        }
      - {
          label: "Tags (pisahkan dengan koma)",
          name: "tags",
          widget: "string",
          required: false,
        }
      - {
          label: "Isi Resep (Bahan & Langkah)",
          name: "body",
          widget: "markdown",
        }
